repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
      - id: ruff-format

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - django-stubs
  # BUG: Issue with pre-commit hooks
  # https://github.com/typeddjango/django-stubs/issues/1087#issuecomment-1208188250

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
