version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mealsmetrics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M



  redis:
    image: redis:7
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M


  worker:
    build: .
    command: celery -A mealsmetrics worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
      - ./media:/app/media
    env_file:
      - .env
    depends_on:
      - redis
      - db
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M


volumes:
  postgres_data:
