name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports: [5432:5432]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mealsmetrics_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports: [6379:6379]

    env:
      DJANGO_SETTINGS_MODULE: mealsmetrics.settings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mealsmetrics_test
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      REDIS_URL: redis://localhost:6379/0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-python-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Install dependencies
        run: uv sync --locked && source .venv/bin/activate

      - name: Run migrations
        run: |
          .venv/bin/python manage.py makemigrations --noinput
          .venv/bin/python manage.py migrate --noinput

      - name: Create media directory
        run: mkdir -p media

      - name: Run tests
        run: .venv/bin/pytest --maxfail=1 --disable-warnings
